using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// 剧情场景启动器：修复 Canvas 缩放，并在缺少控制器时绑定 conversation 面板。
/// 挂载到 Canvas 上。
/// </summary>
[DisallowMultipleComponent]
public class Level1PlotBootstrap : MonoBehaviour
{
    private const string FontPath = "Assets/1_Asset/4_Font/sarasa-gothic-sc-regular.ttf";
    private const string DoctorPanelName = "conversation1";
    private const string GirlPanelName = "conversation2";

    private static readonly string[] DefaultContents =
    {
        "小雨，别怕。爸爸发明的这个小东西，会永远保护你。它会代替你的胰岛，让你再也不用打针了。",
        "爸爸，它会疼吗？",
        "不会的，它比一粒灰尘还小。它会成为你身体的一部分。"
    };

    [SerializeField] private Font dialogueFont;
    [SerializeField] private int dialogueFontSize = 18;
    [SerializeField] private float loadingTextYOffset = -72f;
    [SerializeField] private bool autoSetupOnAwake = true;

    private void Awake()
    {
        FixCanvasTransform();
        EnsurePlotDisplay();

        if (!autoSetupOnAwake)
            return;

        CleanupAutoGeneratedObjects();
        SetupPlotSystem();
    }

    private void FixCanvasTransform()
    {
        RectTransform rect = GetComponent<RectTransform>();
        if (rect.localScale == Vector3.zero)
            rect.localScale = Vector3.one;
    }

    /// <summary>
    /// 只处理背景/加载图铺满，不改动 conversation 布局。
    /// </summary>
    private void EnsurePlotDisplay()
    {
        CanvasScaler scaler = GetComponent<CanvasScaler>();
        if (scaler != null)
        {
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = new Vector2(968f, 544.67f);
            scaler.screenMatchMode = CanvasScaler.ScreenMatchMode.Expand;
            scaler.matchWidthOrHeight = 0.5f;
        }

        SetupFullScreenImage(transform.Find("background"));
        SetupFullScreenImage(transform.Find("loading game"));

        Camera mainCamera = Camera.main;
        if (mainCamera != null)
            mainCamera.backgroundColor = Color.black;
    }

    private static void SetupFullScreenImage(Transform target)
    {
        if (target == null)
            return;

        RectTransform rect = target as RectTransform ?? target.GetComponent<RectTransform>();
        rect.anchorMin = Vector2.zero;
        rect.anchorMax = Vector2.one;
        rect.pivot = new Vector2(0.5f, 0.5f);
        rect.offsetMin = Vector2.zero;
        rect.offsetMax = Vector2.zero;
        rect.anchoredPosition = Vector2.zero;

        Image image = target.GetComponent<Image>();
        if (image != null)
            image.preserveAspect = false;
    }

    private void CleanupAutoGeneratedObjects()
    {
        Transform plotController = transform.Find("PlotController");
        if (plotController != null)
            Destroy(plotController.gameObject);

        Transform dialoguePanel = transform.Find("DialoguePanel");
        if (dialoguePanel != null)
            Destroy(dialoguePanel.gameObject);

        Transform loadingPanel = transform.Find("LoadingPanel");
        if (loadingPanel != null)
            Destroy(loadingPanel.gameObject);
    }

    private void SetupPlotSystem()
    {
        Font font = DialogueFont.Get();
        if (font == null)
        {
            Debug.LogError("Level1PlotBootstrap: 找不到 sarasa 对话字体。");
            return;
        }

        Transform conversation3 = transform.Find("conversation3");
        if (conversation3 != null)
            conversation3.gameObject.SetActive(false);

        HideDuplicateRootDialogueBox();

        DialogueLine[] lines = BuildConversationLines();
        if (lines == null)
            return;

        GameObject loadingPanel = FindOrCreateLoadingPanel(out Text loadingText);

        GameObject controllerGo = new GameObject("PlotController");
        controllerGo.transform.SetParent(transform, false);

        StreamingDialogueController dialogueController = controllerGo.AddComponent<StreamingDialogueController>();
        Level1PlotController plotController = controllerGo.AddComponent<Level1PlotController>();

        dialogueController.Configure(lines);
        plotController.Configure(dialogueController, loadingPanel, loadingText);

        HideUniquePanels(lines);
    }

    private DialogueLine[] BuildConversationLines()
    {
        Transform doctorPanel = transform.Find(DoctorPanelName);
        Transform girlPanel = transform.Find(GirlPanelName);
        if (doctorPanel == null || girlPanel == null)
        {
            Debug.LogError("Level1PlotBootstrap: 找不到 conversation1 或 conversation2。");
            return null;
        }

        Text doctorText = ConversationDialogueHelper.EnsureDialogueText(doctorPanel, DialogueFont.Get(), dialogueFontSize, Color.white);
        Text girlText = ConversationDialogueHelper.EnsureDialogueText(girlPanel, DialogueFont.Get(), dialogueFontSize, Color.white);

        return new[]
        {
            new DialogueLine
            {
                panel = doctorPanel.gameObject,
                dialogueText = doctorText,
                content = DefaultContents[0]
            },
            new DialogueLine
            {
                panel = girlPanel.gameObject,
                dialogueText = girlText,
                content = DefaultContents[1]
            },
            new DialogueLine
            {
                panel = doctorPanel.gameObject,
                dialogueText = doctorText,
                content = DefaultContents[2]
            }
        };
    }

    private static void HideUniquePanels(IEnumerable<DialogueLine> lines)
    {
        HashSet<GameObject> seen = new HashSet<GameObject>();
        foreach (DialogueLine line in lines)
        {
            if (line.panel == null || !seen.Add(line.panel))
                continue;

            line.panel.SetActive(false);
        }
    }

    private void HideDuplicateRootDialogueBox()
    {
        for (int i = 0; i < transform.childCount; i++)
        {
            Transform child = transform.GetChild(i);
            if (child.name == "Image" && child.GetComponent<Image>() != null)
                child.gameObject.SetActive(false);
        }
    }

    private GameObject FindOrCreateLoadingPanel(out Text loadingText)
    {
        Font font = DialogueFont.Get();
        Transform existing = transform.Find("loading game");
        if (existing != null)
        {
            loadingText = existing.GetComponentInChildren<Text>(true);
            if (loadingText == null)
            {
                loadingText = CreateText(existing, "LoadingText", font);
                ApplyLoadingTextLayout(loadingText.rectTransform);
                loadingText.text = "正在加载中...";
                loadingText.fontSize = 36;
                loadingText.fontStyle = FontStyle.Bold;
                loadingText.alignment = TextAnchor.MiddleCenter;
                loadingText.color = Color.white;
            }
            else
            {
                ApplyLoadingTextLayout(loadingText.rectTransform);
                loadingText.font = font;
                loadingText.fontSize = 36;
                loadingText.fontStyle = FontStyle.Bold;
                loadingText.alignment = TextAnchor.MiddleCenter;
                loadingText.color = Color.white;
            }

            existing.gameObject.SetActive(false);
            return existing.gameObject;
        }

        GameObject panel = CreateUiObject("LoadingPanel", transform);
        StretchFull(panel.GetComponent<RectTransform>());

        Image overlay = panel.AddComponent<Image>();
        overlay.color = new Color(0f, 0f, 0f, 0.75f);

        loadingText = CreateText(panel.transform, "LoadingText", font);
        ApplyLoadingTextLayout(loadingText.rectTransform);
        loadingText.text = "正在加载中...";
        loadingText.fontSize = 36;
        loadingText.fontStyle = FontStyle.Bold;
        loadingText.alignment = TextAnchor.MiddleCenter;
        loadingText.color = Color.white;

        panel.SetActive(false);
        return panel;
    }

    private Text CreateText(Transform parent, string name, Font font)
    {
        GameObject go = CreateUiObject(name, parent);
        Text text = go.AddComponent<Text>();
        text.font = font;
        text.text = string.Empty;

        RectTransform rect = text.rectTransform;
        rect.anchorMin = Vector2.zero;
        rect.anchorMax = Vector2.one;
        rect.offsetMin = new Vector2(32f, 12f);
        rect.offsetMax = new Vector2(-32f, -12f);

        return text;
    }

    private static GameObject CreateUiObject(string name, Transform parent)
    {
        GameObject go = new GameObject(name, typeof(RectTransform));
        go.transform.SetParent(parent, false);
        return go;
    }

    private void ApplyLoadingTextLayout(RectTransform textRect)
    {
        textRect.anchorMin = new Vector2(0.5f, 0.5f);
        textRect.anchorMax = new Vector2(0.5f, 0.5f);
        textRect.pivot = new Vector2(0.5f, 0.5f);
        textRect.sizeDelta = new Vector2(800f, 120f);
        textRect.anchoredPosition = new Vector2(0f, loadingTextYOffset);
    }

    private static void StretchFull(RectTransform rect)
    {
        rect.anchorMin = Vector2.zero;
        rect.anchorMax = Vector2.one;
        rect.offsetMin = Vector2.zero;
        rect.offsetMax = Vector2.zero;
    }

#if UNITY_EDITOR
    private void OnValidate()
    {
        if (dialogueFont == null)
            dialogueFont = UnityEditor.AssetDatabase.LoadAssetAtPath<Font>(FontPath);
    }

    private void Reset()
    {
        if (dialogueFont == null)
            dialogueFont = UnityEditor.AssetDatabase.LoadAssetAtPath<Font>(FontPath);
    }
#endif
}
